apiVersion: v1
kind: Secret
metadata:
  name: grafana-db
  namespace: monitoring
type: Opaque
stringData:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: "DB_SERVER_IP:5432"
  GF_DATABASE_NAME: "grafana"
  GF_DATABASE_USER: "postgres"
  GF_DATABASE_PASSWORD: "SOME_SECURE_DB_PASSWORD"
  GF_DATABASE_SSL_MODE: "require"
